export enum SERVER_EVENT_NAME {
  FromServer = "testEvent",
  UserJoinLobby = "userJoinLobby",
  UserJoinedLobby = "userJoinedLobby",
  Notification = "notification",
  UserLeftRoom = "userLeftRoom",
  LobbyUserLeft = "lobbyUserLeft",
  CouldntCreateOrJoinLobby = "lobbyCouldntCreateOrJoin",
  LobbyUserChangedTeam = "lobbyUserChangedTeam",
  LobbySettingsChanged = "lobbySettingsChanged",
  LobbySettingsUpdateFailed = "lobbySettingsUpdateFailed",
  UpdateCardSets = "updateCardSets",
  StartGameFailed = "startGameFailed",
  ErrorCreatingGame = "errorCreatingGame",
  PlayerLeftGame = "playerLeftGame",
  GamePlayerLeft = "gamePlayerLeft",
  GameStarted = "gameStarted",
  GameRoundExplainerPerson = "gameRoundExplainerPerson",
  GameGuessingTeamPlayer = "gameGuessingTeamPlayer",
  GameEnemyTeamPlayer = "gameEnemyTeamPlayer",
  GameUpdateGameTeam = "gameUpdateGameTeam",
}

export enum CLIENT_EVENT_NAME {
  Test = "testEventFromClient",
  CreateLobby = "createLobby",
  JoinLobby = "joinLobby",
  Disconnect = "disconnect",
  Disconnecting = "disconnecting",
  ChangeTeam = "changeTeam",
  LobbyUpdateSettings = "lobbyUpdateSettings",
  TryStartGame = "lobbyTryStartGame",
  GameSkipCard = "gameSkipCard",
  GameValidAnswer = "gameValidAnswer",
  GameForbiddenWordUsed = "gameForbiddenWordUsed",
}
