version: '3.7'

services:
  tabu-online-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: tabu-online-server
    expose:
      - '3010'
    ports:
      - '3010:3010'
    command: yarn run dev
